# PyInstaller spec for the Keystone agent.
#
# Build with:  py -3.12 -m PyInstaller installer/keystone-agent.spec
# Output:      installer/dist/KeystoneAgent/KeystoneAgent.exe
#
# Phase 0: onefolder (faster dev iteration, easier to debug with
# attached logs). Phase 4 may switch to --onefile for a tidier MSI.
# flake8: noqa

block_cipher = None

# ── Write build metadata before Analysis ──────────────────────────────── #
# Injects the current git short sha + timestamp into agent/_build.py so
# the running exe can report its exact commit. The file is checked into
# the repo with defaults ("dev") and overwritten on every build.
import subprocess as _sp
from datetime import datetime as _dt, timezone as _tz
from pathlib import Path as _Path

try:
    _sha = _sp.check_output(
        ["git", "rev-parse", "--short=7", "HEAD"],
        cwd=str(_Path(SPECPATH).parent),
    ).decode().strip()
except Exception:
    _sha = "dev"

_built = _dt.now(_tz.utc).strftime("%Y-%m-%dT%H:%M:%SZ")
_build_py = _Path(SPECPATH).parent / "agent" / "_build.py"
_build_py.write_text(
    f'"""Auto-generated by keystone-agent.spec — DO NOT EDIT."""\n\n'
    f'GIT_SHA = "{_sha}"\n'
    f'BUILT_AT = "{_built}"\n',
    encoding="utf-8",
)
print(f"[spec] agent/_build.py: GIT_SHA={_sha} BUILT_AT={_built}")

a = Analysis(
    ['launcher.py'],
    pathex=['..'],
    binaries=[],
    datas=[
        # Ship the default config snapshot with the installer so a
        # freshly-installed agent has something to run against before
        # the operator imports any templates. Resolved at runtime via
        # sys._MEIPASS when frozen — see agent.paths.config_dir().
        ('..\\config', 'config'),
    ],
    hiddenimports=[
        'uvicorn.logging',
        'uvicorn.loops',
        'uvicorn.loops.auto',
        'uvicorn.protocols',
        'uvicorn.protocols.http',
        'uvicorn.protocols.http.auto',
        'uvicorn.protocols.websockets',
        'uvicorn.protocols.websockets.auto',
        'uvicorn.lifespan',
        'uvicorn.lifespan.on',
        'pydantic',
        'httpx',
        'win32crypt',
        'win32serviceutil',
        'win32service',
        'win32event',
        'servicemanager',
    ],
    hookspath=[],
    hooksconfig={},
    runtime_hooks=[],
    excludes=[
        'tkinter',
        'matplotlib',
        'PyQt5',
        'PyQt6',
        'PySide2',
        'PySide6',
    ],
    win_no_prefer_redirects=False,
    win_private_assemblies=False,
    cipher=block_cipher,
    noarchive=False,
)
pyz = PYZ(a.pure, a.zipped_data, cipher=block_cipher)

exe = EXE(
    pyz,
    a.scripts,
    [],
    exclude_binaries=True,
    name='KeystoneAgent',
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=False,
    console=True,
    disable_windowed_traceback=False,
    argv_emulation=False,
    target_arch=None,
    codesign_identity=None,
    entitlements_file=None,
    # Phase 4: icon='keystone.ico', version='version_info.txt'
)

coll = COLLECT(
    exe,
    a.binaries,
    a.zipfiles,
    a.datas,
    strip=False,
    upx=False,
    upx_exclude=[],
    name='KeystoneAgent',
)
